### PR TITLE
Feature allow alpha, beta, & RC

### PR DESCRIPTION
**Pull request by kohenkatz**
PR with tests for #599

### CODE REVIEW

**Comment by c9s** [comment]
Why delete `.pharcc.yml`?

**Comment by c9s** [comment]
Please reset `phpbrew` phar file from this PR since it will be compiled when rolling out new release

**Comment by c9s** [comment]
If you want to remove `pharcc`, please open another PR to remove. PRs should be simple and contain only one subject

**Comment by kohenkatz** [comment]
I deleted `.pharcc.yml` because CLIFramework 2.8 (which fixes the bug with building the phar) and pharcc aren't compatible with each other because they require conflicting versions of `symfony.yaml`.  I will open a new PR to fix #561 which deletes that old stuff.

**Comment by c9s** [comment]
Thanks!

**Pull request closed without merging**
