### PR TITLE
Correct a typo on the README file

### PR DESCRIPTION
**Pull request by bpineda**
Correct a typo and add an additional instruction to users using MacOS Sierra systems

### CODE REVIEW

**Comment by nrebhun** [comment]
Hey @bpineda,

Thanks for finding this as well!

I've [already opened a PR](https://github.com/phpbrew/phpbrew/pull/838) resolving this for the English README as well as the Japanese README.

Additionally, there's a bit more to this particular correction: El Capitan is subject to this issue as well.

**Comment by bpineda** [comment]
No problem, man. And now that you mention it, I could work on the README in Spanish.

**Comment by c9s** [comment]
It's conflicted.

**Comment by c9s** [comment]
Hi @bpineda any update of this PR? or I might have to close this PR.

**Comment by jhdxr** [comment]
Hello @bpineda , I'm closing this PR because every change in this PR has already been apllied to master through other PR or commits.  Thank you for your effort and concern any way.

**Pull request closed without merging**
