### PR TITLE
App store update

### PR DESCRIPTION
**Pull request by peteraba**
Updating  behat3 and box2 versions, fixing behat-3 app name.

### CODE REVIEW

**Comment by peteraba** [comment]
@c9s please let me know if you think I need to fix something, but I guess the tests are broken.

**Comment by c9s** [comment]
@peteraba looks like it doesn't work for php7

**Comment by c9s** [comment]
could you migrate PHPUnit_Framework_TestCase to `PHPUnit\Framework\TestCase`? because travis ci upgraded phpunit to phpunit 6 I think.

**Comment by peteraba** [comment]
@c9s sorry, I missed your message. I could change that, but:
1. I don't think it has anything to do with my PR
2. It might break other tests I guess.

**Pull request merged**
