### PR TITLE
Fix phpbrew bash prompt for php 8

### PR DESCRIPTION
**Pull request by jrmgx**
This is a basic fix.
Note: I did not find the related code for other shell prompt (they may even not have a similar option)
if it exists it could be done in a separate PR

### CODE REVIEW

**Review by jhdxr — APPROVED** [review]
LGTM

**Comment by jhdxr** [comment]
Thanks. The fish shell script has similar functions (https://github.com/phpbrew/phpbrew/blob/bd6d47cdfc9c64d7384be057ecaba8ea6e2ba317/shell/phpbrew.fish#L487) but no worry, I'll update it.

**Comment by jhdxr** [comment]
hmm, I think travis-ci.org is dead. @c9s Can you help to configure it optional?

**Comment by peter279k** [comment]
> hmm, I think travis-ci.org is dead. @c9s Can you help to configure it optional?

As far as I know, Travis CI change travis-ci.org to travis-ci.com for about whiles. And it's not friendly for open source projects since then.

IMHO, I think it's time to switch to the GitHub Actions now :).

**Comment by c9s** [comment]
let me remove the travis ci require

**Comment by c9s** [comment]
thank you all!

**Pull request merged**
