### PR TITLE
self-update download to a tmp file first instead of overwrite the exi…

### PR DESCRIPTION
**Pull request by jhdxr**
fix issue #524

### CODE REVIEW

**Comment by marcioAlmada** [comment]
Looks ok to me

:+1:

**Comment by c9s** [comment]
LTGM

**Comment by jhdxr** [comment]
what's the meaning of LTGM?...

**Comment by marcioAlmada** [comment]
LTGM means "learn the game mechanics"... confused. @c9s probably meant LGTM = looks good to me.

**Pull request merged**
