### PR TITLE
Update git install examples

### PR DESCRIPTION
**Pull request by Rockstar04**
This would have saved me about 45 minutes of source code tracing / trial and error

### CODE REVIEW

**Comment by marcioAlmada** [comment]
Thank you! And sorry, I'm not having much time to dedicate to this project lately.

**Comment by marcioAlmada** [comment]
@c9s maybe we could do something about that?

**Comment by Rockstar04** [comment]
Sorry, I didnt mean for that to sound snarky (but reading it again it does sound that way).

**Comment by marcioAlmada** [comment]
Np. I didn't get it that way :)

**Comment by c9s** [comment]
@marcioAlmada no problem. but I haven't try the php7 install command :p

**Pull request merged**
