### PR TITLE
Added phpdocumentor to `phpbrew app` aka the AppStore

### PR DESCRIPTION
**Pull request by jasny**
[PhpDocumentor](https://phpdoc.org) allows generating documentation from source files.

Also added missing `psych` to bash completion.

### CODE REVIEW

**Comment by kevinnio** [comment]
@jasny please rebase `master` so you're Travis build get fixed.

**Comment by theofidry** [comment]
Rather than trying to keep this list up to date, would it make sense to switch to PHIVE instead? Maybe phpbrew could ship PHIVE natively.

**Comment by jasny** [comment]
@kevinnio Sorry, I missed it was still failing. Fixed it now.

**Comment by c9s** [comment]
@jasny it's conflicted, can you please check? thanks~

**Comment by jasny** [comment]
@c9s Can this be merged?

**Comment by morozov** [comment]
Thank you, @jasny.

**Pull request merged**
