### PR TITLE
Fixed system interpreter leaked issue #1134.

### PR DESCRIPTION
**Pull request by markwu**
Use exec() to run php code with used interpreter instead of system interpreter.

### CODE REVIEW

**Comment by markwu** [comment]
The result:

```
$ phpbrew list
* php-7.4.1
  php-7.3.13
  php-5.6.40

$ phpbrew system
/Users/mark/.phpbrew/php/php-7.3.13/bin/php

$ phpbrew list-ini
Loaded ini files:
 - /Users/mark/.phpbrew/php/php-7.4.1/var/db/ast.ini
 - /Users/mark/.phpbrew/php/php-7.4.1/var/db/gd.ini
 - /Users/mark/.phpbrew/php/php-7.4.1/var/db/opcache.ini
 - /Users/mark/.phpbrew/php/php-7.4.1/var/db/xdebug.ini
```

**Comment by markwu** [comment]
`phpbrew info` has the same problem, too.

**Comment by markwu** [comment]
I try to wrap the function, so I can get the function call through used php interpreter like following. We can get exact the same result as before.

```php
UsePhpFunctionWrapper::execute('php_ini_loaded_file()', $output) ? $file = $output : $file = '';
```

```php
<?php

namespace PhpBrew;
use PhpBrew\Config;

class UsePhpFunctionWrapper
{
    public static function execute($func, &$output = null)
    {
        $retVal = false;

        $command = Config::getCurrentPhpBin() . '/php';

        $descriptorspec = array(
           0 => array("pipe", "r"),
           1 => array("pipe", "w"),
           2 => array("pipe", "w")
        );

        $process = proc_open($command, $descriptorspec, $pipes);

        if (is_resource($process)) {
            fwrite($pipes[0], '<?php echo serialize(' . $func  .'); ?>');
            fclose($pipes[0]);

            $output = stream_get_contents($pipes[1]);
            fclose($pipes[1]);

            $retVal = proc_close($process);

            if ($retVal === 0) {
                $output = unserialize($output);

                return true;
            }
        }

        return false;
    }
}
```

**Comment by markwu** [comment]
`phpbrew config`, `phpbrew list-ini` and `phpbrew info` fixed.

**Comment by morozov** [comment]
This looks even more complicated than I thought it would. We can do it much simpler:
1. `phpbrew config` could be implemented as:
   ```sh
   # Bash
   $ command $EDITOR "$(php -r "echo php_ini_loaded_file();")"

   # Fish
   $ command $EDITOR (php -r "echo php_ini_loaded_file();")
   ```
2. `phpbrew info` currently excutes a series of subsequent calls to the underlying PHP and glues the output together. Instead, we could do something like:
   ```
   # phpbrew info-script generates some script
   $ phpbrew info-script
   <?php
   
   echo 'Version' . PHP_EOL;
   echo 'PHP-' . phpversion() . PHP_EOL;
   // and so on

   # its output gets piped to the currently used PHP
   phpbrew info-script | php
   ```

**Comment by markwu** [comment]
Yes, you are right, it's much simpler. I just tried to keep everything as before.

But, I am not so familiar with the shell scripts. I will leave the implement for you, and see If I can catch how you do it.

**Comment by morozov** [comment]
Closing in favor of #1136.

**Pull request closed without merging**
